version: '3'
services:
  mysql:
    image: mariadb:10.3.17
    command: --max_allowed_packet=256M
    volumes:
      - "./data/db:/var/lib/mysql:delegated"
    ports:
       - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jZRgq5SE8kE7
  litespeed:
    image: litespeedtech/openlitespeed:1.6.15-lsphp74
    env_file:
      - .env
    volumes:
        - ./php.ini:/usr/local/lsws/lsphp74/etc/php/7.4/litespeed/php.ini
        - ./lsws/conf:/usr/local/lsws/conf
        - ./lsws/admin-conf:/usr/local/lsws/admin/conf
        - ./bin/container:/usr/local/bin
        - ./sites:/var/www/vhosts/
        - ./acme:/root/.acme.sh/
        - ./logs:/usr/local/lsws/logs/
        - ./letsencrypt:/etc/letsencrypt/
    ports:
        - 80:80
        - 443:443
        - 7080:7080
        - 143:143
        - 110:110
        - 26:26
        - 993:993
        - 995:995
        - 465:465
  
    restart: always
    environment:
      TZ: Asia/Dhaka
  phpmyadmin:
    #image: bitnami/phpmyadmin:latest
    image: bitnami/phpmyadmin:5.0.2-debian-10-r72
    ports:
      - 8080:80
      - 8443:443
    environment:
        DATABASE_HOST: mysql
